services:
  app:
    image: composer:2
    container_name: buyandbye_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - buyandbye_network

  php:
    image: php:8.2-cli
    container_name: buyandbye_php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - buyandbye_network

  postgres:
    image: postgres:16
    container_name: buyandbye_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-buyandbye}
    command: >
      postgres
      -c app.db_user=${DB_USERNAME:-app}
      -c app.db_password=${DB_PASSWORD:-password}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - buyandbye_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: buyandbye_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - buyandbye_network

volumes:
  postgres_data:
    driver: local

networks:
  buyandbye_network:
    driver: bridge
